### ISSUE TITLE
Not working with Swift 3.0

### ISSUE THREAD

**Issue by fabioiegri** [willowtreeapps/WillowTreeReachability#4]
Hi, 
WillowTreeReachability doesn't work with swift 3.

:(

**Comment by fabioiegri** [comment]
Hello eriklamanna. Thank You for your work and for fast reply.

The update via cocoapods ins't working, but I solved (editing my local files ) using your last update.

Thank You very much 
Kind regards
Fabio

**Comment by eriklamanna** [comment]
Fabio, since it wasn't merged yet that's why it was not updated on cocoa pods. It should be there now as version 2.0.0

**Comment by fabioiegri** [comment]
Good morning eriklamanna. Thank You for reply. 
👍 I was already happy also without cocoa pods ... so, I'm much more happy now.
I confirm to you that this morning the cocoa pods update has worked correctly. 

This is a great library.

Thank You again
Have a nice day
Kind regards
Fabio
